services:
  - type: web
    name: linebot
    env: python
    buildCommand: pip install -r requirements.txt
    startCommand: python main.py
    envVars:
      - key: LINE_CHANNEL_ACCESS_TOKEN
        value: "ใส่ access token จริงที่นี่"
